log:
  level: debug
connector:
  blockchain:
    rpc: https://ghostnet.ecadinfra.com
    network: ghostnet
persistence:
  leveldb:
    # path: ./.leveldb // SET BY ENV VARIABLE
ffcore:
  url: http://127.0.0.1:5101
  namespaces:
    - tezos
confirmations:
  required: 0
transactions:
  handler:
    name: simple
    simple:
      fixedGasPrice: 0
      gasOracle:
        mode: fixed